package com.mall.sls.common;

import retrofit2.http.PUT;

public class RequestUrl {
    public static String APP_URL_INFO_URL="/app/version/android";
    public static String LOGIN_IN_URL="/app/auth/login/code";//登录
    public static String ONE_CLICK_LOGIN_URL="/app/auth/login/ali";//一键登录
    public static String SEND_CODE_V_URL="/app/auth/regCaptcha";//发送验证码
    public static String USER_RP_STATUS_URL="/app/certify";//获取用户认证状态
    public static String HOME_INDEX_URL="/app/home/index";//首页信息
    public static String GOODS_DETAILS_URL="/app/goods/detail";//商品详情
    public static String ADDRESS_MANAGE_URL="/app/address/list";//地址列表
    public static String CUSTOMER_PHONE_URL="/app/common/customer";//客服电话
    public static String COMMON_AREA_URL="/app/common/area";//获取所有三级地址
    public static String ADDRESS_SAVE_URL="/app/address/save";//添加地址
    public static String DELETE_ADDRESS_URL="/app/address/";//删除地址
    public static String CART_FAST_ADD_URL="/app/cart/fastadd";//商品购买接口
    public static String CART_CHECKOUT_URL="/app/cart/checkout";//订单预提交
    public static String COUPON_SELECT_LIST_URL="/app/coupon/selectlist";//查询当前预提交订单可用优惠券
    public static String ORDER_UBMIT_URL="/app/order/submit";//提交订单
    public static String COUPON_MY_LIST_URL="/app/coupon/mylist";//优惠卷列表
    public static String MINE_INFO_URL="/app/auth/info";//我的
    public static String LOCAL_GOODS_URL="/app/goods";//本地拼团
    public static String GET_CERTIFY_ID_URL="/app/certify";//实人认证
    public static String ORDER_LIST="/app/order/list";//订单列表
    public static String ORDER_DETAILS="/app/order/detail";//订单详情
    public static String AUTH_INVITER="/app/auth/inviter";//我的邀请
    public static String MES_TYPE_URL="/app/msg/type";//获取消息类型
    public static String MSG_LIST_URL="/app/msg/list";//获取用户消息列表
    public static String MSG_EMPTY_URL="/app/msg/empty";//清空消息
    public static String MSG_CHANGE_STATUS="/app/msg/changeStatus";//设置消息为已读
    public static String GROUPON_URL="/app/groupon";//我的拼团
    public static String VIP_GROUPONS_URL="/app/goods/vipGroupons";//超级会员专享团购
    public static String ALIPAY_URL="/app/user/pay/appPay";//支付超级会员和实人认证
    public static String GROUP_REMIND_URL="/app/goods/groupRemind";//活动团开团提醒
    public static String VIP_OPEN_URL="/app/vip/open";//开通超级会员
    public static String ORDER_ALIPAY="/app/order/pay";//支付宝支付订单
    public static String LOGIN_WEIXIN_URL="/app/auth/login/wx/code";//微信登录
    public static String INVITATION_CODE_URL="/app/common/invitationCode";//获取默认的推荐码
    public static String BIND_SMS_CODE_LOGIN="/app/auth/login/wx/phone";//app微信绑定手机号登陆
    public static String BIND_ONE_CLICK="/app/auth/login/wx/ali";//阿里一键登录接口(绑定微信)
    public static String VIP_PAY_AMOUNT ="/app/common/payAmount";//查询认证或者超级会员支付金额
    public static String WX_GOODS_DETAILS="/app/goods/grouponDetail";//H5团购详情
    public static String AUTH_SHARE_URL="/app/auth/share";//分享信息
    public static String WX_INVITATION_CODE="/app/auth/invitationCode";//获取邀请码和h5链接地址
    public static String ADD_FEED_BACK_URL="/app/auth/addFeedBack";//意见反馈
    public static String USER_PAY_WX="/app/user/pay/wx";//微信支付实人认证和超级会员
    public static String ORDER_WX_PAY="/app/order/wxPay";//微信支付订单
    public static String ORDER_CANCEL="/app/order/cancel";//订单取消
    public static String BIND_WX="/app/auth/bindWx";//绑定微信
    public static String PRIZE_LIST="/app/prize/list";//抽奖列表
    public static String SYSTEM_TIME="/app/prize/systemTime";//获取系统时间
    public static String PRIZE_RESULT="/app/prize/prizeResult";//抽奖结果
    public static String JOIN_PRIZE="/app/prize/joinPrize";// 参与抽奖
    public static String PRIZE_HISTORY="/app/prize/history";//开奖历史
    public static String COUPON_RECEIVE="/app/coupon/receive";//领取优惠卷
    public static String CART_COUNT="/app/cart/general/count";//查询购物车商品数量
    public static String CART_ADD="/app/cart/general/add";//加入购物车
    public static String CART_GENERAL_CHECKED="/app/cart/general/checked";//购物车选中商品购买
    public static String DELETE_CART_ITEM="/app/cart/general/delete/";//删除购物车item
    public static String CART_GENERAL_LIST ="/app/cart/general/list";//查询购物车列表
    public static String CART_UPDATE_NUMBER="/app/cart/general/update";//修改购物车商品数量
    public static String GOODS_BASE_GOOD="/app/goods/baseGood";//普通商品详情
    public static String CART_FAST_ADD="/app/cart/general/fastadd";//立即购买
    public static String ORDER_GENERAL_SUBMIT="/app/order/general/submit";//普通商品下单
    public static String ORDER_LOGISTICS="/app/order/logistics/";//查询物流接口
    public static String ADD_CART_BATCH="/app/order/general/addCartBatch";//订单详情加入购物车
    public static String GOODS_RUSH_BUY="/app/goods/rushBuy";//正在疯抢
    public static String GOODS_WAIT_BUY="/app/goods/waitBuy";//即将开抢
    public static String SNAP_UP ="/app/home/snap-up";//拼团抢购列表
    public static String FIRST_CATEGORY="/app/goods/categories-l1";//商品L1类目列表
    public static String SECOND_CATEGORY="/app/goods/l1/";//根据L1类目过滤配置数量的商品
    public static String GOODS="/goods";//根据L1类目过滤配置数量的商品
    public static String SECOND_CATEGORY_ITEM ="/app/goods/l2/";//根据L2类目过滤全部商品
    public static String SEARCH_GOODS="/app/goods/search";//关键字搜索
    public static String SEARCH_HISTORY="/app/goods/search-history";//商品搜索历史记录
    public static String BANK_CARD_LIST="/app/baofoo/list";//查询绑定的银行卡记录
    public static String CARD_INFO="/app/baofoo/card-info";//查询银行卡的属性信息
    public static String START_BANK_BIND="/app/baofoo/begin-sign";//开始绑定银行卡
    public static String CONFIRM_BANK_BIND="/app/baofoo/confirm-sign";//确认绑定银行卡
    public static String BANK_BEGIN="/app/baofoo/";//
    public static String BANK_UNTIE="/cancel-sign";//解绑银行卡
    public static String BAO_FOO_SINGLE_PAY="/app/baofoo/single-pay";//宝付直接支付
    public static String SEND_BAO_FU_CODE="/public/f/code/baofoo";//获取宝付支付验证码
    public static String CERTIFY_INFO="/app/auth/certify-info";//获取用户认证的信息
    public static String ORDER_ADD_CART="/app/order/general/add-cart";//普通商品订单再来一单
    public static String INVITATION_OPEN="/app/common/invitation-open";//是否打开邀请码
    public static String PAY_METHOD="/app/common/pay-method";//获取支付方式
    public static String BEGIN_PAY="/app/pay/begin-pay";//开始支付

}
